### ISSUE TITLE
Type not found : Main

### ISSUE THREAD

**Issue by ghost** [FurretDev/hxdiscord#4]
![Help](https://user-images.githubusercontent.com/109828559/213945593-3bab8196-fb2e-4d7a-a00c-a65e4c01e7c2.png)
So i followed the Furret tutorial, but for some reason it's giving the error. I added the Main.hx on scp, but did i missed something?

**Comment by ghost** [comment]
Nevermind, im dumb

**Comment by furretpaws** [comment]
You forgot to add this in the hxml file
`-main Main`
