### ISSUE TITLE
Quick Question about Embeds

### ISSUE THREAD

**Issue by WizardMantis441** [FurretDev/hxdiscord#5]
quick question, are there any examples on how to use embeds?

i found these typedefs but i'm not sure how to actually implement these into a sent message.
![image](https://user-images.githubusercontent.com/77557487/215286562-ac744986-176a-4003-99cb-9347ce3f69eb.png)

how would i alter this to send an embed?
`m.reply({content: "Pong!"}, false);`

**Comment by swordcube** [comment]
okay so basically
```haxe
m.reply({embeds: [
{
title: "shit",
description: "nuts"
}
]});
```

**Comment by WizardMantis441** [comment]
oh sick

**Comment by furretpaws** [comment]
I know this is a closed issue, but there's 2 ways actually if you want to send an embed.

You can use this website as it gives you the embed as a json
https://glitchii.github.io/embedbuilder/

Or, you can also make an embed variable, like this

```haxe
var embed = new hxdiscord.types.Embed();
embed.setTitle("Title");
embed.setDescription("Description");

m.reply({embeds: [embed]}, true);
```
